export const fields = [
  {
    name: "address",
    type: "text",
    label: "Enter your Address",
    placeholder: "Enter your address",
    required: true,
    error: "Please enter your address",
  },
  {
    name: "bio",
    type: "textarea",
    label: "Enter your Bio",
    placeholder: "Enter your bio",
    required: true,
    error: "Please enter your bio",
  },
  {
    name: "biker_type",
    type: "text",
    label: "What kind of biker are you?",
    placeholder: "What kind of biker are you?",
    required: true,
    error: "Please enter your biker type",
  },
  {
    name: "bike_count",
    type: "text",
    label: "How many bikes do you own?",
    placeholder: "How many bikes do you own?",
    required: true,
    error: "Please enter your bike count",
  },
  {
    name: "phone",
    type: "text",
    label: "Enter your phone number",
    placeholder: "Enter your phone number",
    required: true,
    error: "Please enter your phone number",
  },
  {
    name: "current_bike",
    type: "text",
    label: "Enter your current bike",
    placeholder: "Enter your current bike",
    required: true,
    error: "Please enter your current bike",
  },
  {
    name: "zip_code",
    type: "text",
    label: "Enter your Zip Code",
    placeholder: "Enter your zip code",
    required: true,
    error: "Please enter your zip code",
  },
  {
    name: "fav_trail",
    type: "text",
    label: "Enter your favorite trail",
    placeholder: "Enter your favorite trail",
    required: true,
    error: "Please enter your favorite trail",
  },
];
